### Import and Export Data with Python

See additional information on working with data in [Begin Python](https://github.com/APMonitor/begin_python) and [Data Science](https://github.com/APMonitor/data_science) Courses.

#### Method 1: Pandas

In [1]:
import pandas as pd
url = 'http://apmonitor.com/pdc/uploads/Main/tclab_data2.txt'
data = pd.read_csv(url)
data.head()

Time   Q1   Q2     T1     T2
0     0  0.0  0.0  19.93  19.25
1     1  0.0  0.0  19.93  19.29
2     2  0.0  0.0  19.96  19.29
3     3  0.0  0.0  19.93  19.29
4     4  0.0  0.0  19.93  19.29

In [2]:
data.to_csv('file.csv')

#### Method 2: Numpy

In [3]:
import numpy as np
data = np.loadtxt('file.csv',delimiter=',',skiprows=1)
print(data)

[[  0.     0.     0.     0.    19.93  19.25]
 [  1.     1.     0.     0.    19.93  19.29]
 [  2.     2.     0.     0.    19.96  19.29]
 ...
 [598.   598.    50.    80.    68.82  50.64]
 [599.   599.    50.    80.    68.92  50.42]
 [600.   600.    50.    80.    68.75  50.51]]


In [4]:
np.savetxt('file2.csv',data,delimiter=',',\
           comments='',header='Time,Q1,Q2,T1,T2')